### ISSUE TITLE
Show Item Rate in Item List

### ISSUE THREAD

**Issue by mascor** [gaurav-naik/idr_erpnext#9]
Hi,
actually, Item List shows:
- Item Name
- Status
- Item Group 
- Item Code
- Something that I cannot understand seems the hour since I created it

The list should show these fields:
- Item Code
- Item Name
- Item Group
- Rate

If I use "Customize Form" to customize these fields is a problem? I cannot remember what we should to avoid losing these changes after bench update.
Thanks

**Comment by mascor** [comment]
I was able to setup the list in this way:

- Item Name
- Status
- Item Group
- Rate

but cannot move Item Code as the first field and remove Status.

**Comment by gaurav-naik** [comment]
Status is a default field in Item List and should not be removed if not absolutely necessary.
Customize form is the correct way to set the fields which will be shown in the list.

Closing this issue.
